export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transacrions with zero fees',
    description: 'Get access to our exlusive app that allows you to send unlimited transactions without get any charged any fees',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/svg-1.svg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
};
